//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recommendations
    {
        public int recommendationId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> Professional { get; set; }
        public Nullable<System.DateTime> RecommendationDate { get; set; }
        public Nullable<bool> IsEnable { get; set; }
        public Nullable<int> RatePrice { get; set; }
        public Nullable<int> RateProfessionalism { get; set; }
        public Nullable<int> RateArrival { get; set; }
        public string Comments { get; set; }
    
        public virtual Professionals Professionals { get; set; }
        public virtual Users Users { get; set; }
    }
}
