//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserSearch
    {
        public int UserSearchId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> Professional { get; set; }
        public Nullable<System.DateTime> SearchDate { get; set; }
    
        public virtual Professionals Professionals { get; set; }
        public virtual Users Users { get; set; }
    }
}
